### ISSUE TITLE
`pip install cloudflare-ddns` fails

### ISSUE THREAD

**Issue by luckydonald** [shlinx/cloudflare-ddns#2]
```sh
$ pip install cloudflare-ddns
Collecting cloudflare-ddns
  Downloading cloudflare-ddns-1.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-OxHmYX/cloudflare-ddns/setup.py", line 6, in <module>
        with open(os.path.join(base, 'README.rst'), encoding='utf-8') as readme:
    TypeError: 'encoding' is an invalid keyword argument for this function

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-OxHmYX/cloudflare-ddns/

$ python -V
Python 2.7.12
```

**Comment by shlinx** [comment]
Hi @luckydonald, this package only works for python 3, it doesn't work for python 2.

**Comment by luckydonald** [comment]
Ah, okey. Indeed it worked with python 3
